### ISSUE TITLE
Support custom path of PrismaClient

### ISSUE THREAD

**Issue by pwdevbcf** [47ng/prisma-field-encryption#19] opened 2022-05-10 15:59 UTC
Is there a possibility to add support for custom path of prisma client? 

I am using prisma client like that: `import { PrismaClient } from './prisma/dir/generated/generalClient';`

because of multiple connections. 
Is there any possibility to add new configuration property like: 
```
prisma.$use(fieldEncryptionMiddleware(
prismaClient: mainPrismaClient
))
```

because @prisma/client is not that much flexible

**Comment by franky47** [comment] 2022-05-10 16:11
Duplicate of #18, let's move the discussion there.

**Closed by franky47** 2022-05-10 16:11 UTC
